In [1]:
import numpy as np
arr = np.array([1, 2, 3, 4, 5])

In [2]:
print(arr)

[1 2 3 4 5]


In [7]:
arr = np.array([10, 20, 30, 40, 50, 60])
bool_index = arr > 30
print(bool_index)

[False False False  True  True  True]


In [8]:
filtered_arr = arr[bool_index]
print(filtered_arr)

[40 50 60]


In [9]:
print(arr[arr > 30])

[40 50 60]


In [10]:
arr2d = np.array([[5, 10], [15, 20], [25, 30]])
print(arr2d[arr2d > 15])

[20 25 30]


In [11]:
array1 = np.array([12, 24, 16, 21, 32, 29, 7, 15])
array1

array([12, 24, 16, 21, 32, 29,  7, 15])

In [12]:
boolean_mask = array1 > 20
boolean_mask

array([False,  True, False,  True,  True,  True, False, False])

In [13]:
boolean_mask = array1 % 2 != 0
boolean_mask

array([False, False, False,  True, False,  True,  True,  True])

In [14]:
boolean_mask = array1 % 2 != 0
result = array1[boolean_mask]
result

array([21, 29,  7, 15])

In [17]:
np.random.seed(100)
arr_x = np.random.rand(10) * 100
arr_x

array([54.34049418, 27.83693851, 42.45175907, 84.47761323,  0.47188562,
       12.15691208, 67.07490847, 82.58527551, 13.67065897, 57.50933294])

In [18]:
mask = arr_x >50
mask

array([ True, False, False,  True, False, False,  True,  True, False,
        True])

In [19]:
arr_x[mask]

array([54.34049418, 84.47761323, 67.07490847, 82.58527551, 57.50933294])